### ISSUE TITLE
Participante visualiza workshops disponíveis

### ISSUE THREAD

**Issue by joaorsalmeida** [guru-br/workshop-subscription-system#3]
Visitantes podem visualizar os workshops disponíveis e que ainda aceitam inscrições;

**Comment by gionaufal** [comment]
Estou nessa, mais tarde envio o PR :)

Além de só mostrar os workshops disponíveis (com data no futuro e que ainda tenham vagas), algum outro requisito? Pensei em somente não mostrar a descrição completa e talvez a quantidade máxima de participantes, mas as outras informações acho que são importantes.
